/**
 * API routes for the orchestrator.
 */

import { Router } from "express";
import { atsRouter } from "./routes/ats";
import { authRouter } from "./routes/auth";
import { backupRouter } from "./routes/backup";
import { batchRouter } from "./routes/batch";
import { careerOpsRouter } from "./routes/career-ops";
import { coverLetterRouter } from "./routes/cover-letter";
import { databaseRouter } from "./routes/database";
import { demoRouter } from "./routes/demo";
import { designResumeRouter } from "./routes/design-resume";
import { extractorHealthRouter } from "./routes/extractor-health";
import { ghostwriterRouter } from "./routes/ghostwriter";
import { interviewPrepRouter } from "./routes/interview-prep";
import { interviewStoriesRouter } from "./routes/interview-stories-router";
import { jobsRouter } from "./routes/jobs";
import { livenessRouter } from "./routes/liveness";
import { manualJobsRouter } from "./routes/manual-jobs";
import { negotiationRouter } from "./routes/negotiation";
import { offerEvaluationRouter } from "./routes/offer-evaluation";
import { onboardingRouter } from "./routes/onboarding";
import { outcomeLearningRouter } from "./routes/outcome-learning";
import { patternAnalysisRouter } from "./routes/pattern-analysis";
import { pipelineRouter } from "./routes/pipeline";
import { portalScannerRouter } from "./routes/portal-scanner";
import { postApplicationProvidersRouter } from "./routes/post-application-providers";
import { postApplicationReviewRouter } from "./routes/post-application-review";
import { profileRouter } from "./routes/profile";
import { settingsRouter } from "./routes/settings";
import { tracerLinksRouter } from "./routes/tracer-links";
import { visaSponsorsRouter } from "./routes/visa-sponsors";
import { watchlistRouter } from "./routes/watchlist";
import { webhookRouter } from "./routes/webhook";
import { workdayRouter } from "./routes/workday";
import { workspacesRouter } from "./routes/workspaces";

export const apiRouter = Router();

apiRouter.use("/jobs", jobsRouter);
apiRouter.use("/liveness", livenessRouter);
apiRouter.use("/jobs/:id/chat", ghostwriterRouter);
apiRouter.use("/demo", demoRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/pipeline", pipelineRouter);
apiRouter.use("/post-application", postApplicationProvidersRouter);
apiRouter.use("/post-application", postApplicationReviewRouter);
apiRouter.use("/manual-jobs", manualJobsRouter);
apiRouter.use("/webhook", webhookRouter);
apiRouter.use("/profile", profileRouter);
apiRouter.use("/database", databaseRouter);
apiRouter.use("/design-resume", designResumeRouter);
apiRouter.use("/visa-sponsors", visaSponsorsRouter);
apiRouter.use("/onboarding", onboardingRouter);
apiRouter.use("/backups", backupRouter);
apiRouter.use("/batch", batchRouter);
apiRouter.use("/tracer-links", tracerLinksRouter);
apiRouter.use("/workspaces", workspacesRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/workday", workdayRouter);
apiRouter.use("/watchlist", watchlistRouter);
apiRouter.use("/cover-letter", coverLetterRouter);
apiRouter.use("/offer-evaluation", offerEvaluationRouter);
apiRouter.use("/negotiation", negotiationRouter);
apiRouter.use("/ats", atsRouter);
apiRouter.use("/portal-scanner", portalScannerRouter);
apiRouter.use("/pattern-analysis", patternAnalysisRouter);
apiRouter.use("/outcome-learning", outcomeLearningRouter);
apiRouter.use("/career-ops", careerOpsRouter);
apiRouter.use("/interview-stories", interviewStoriesRouter);
apiRouter.use("/interview-prep", interviewPrepRouter);
apiRouter.use("/", extractorHealthRouter);
